image: gitpod/workspace-full-vnc

tasks:
  - name: InventoryManagement
    init: |
      docker run --restart always -d --name=mysql -p 127.0.0.1:3306:3306 -e MYSQL_ROOT_PASSWORD=root mysql:8
      sudo apt update
      sudo apt install -y mysql-client
      sdk install java 17.0.3-ms < /dev/null
      sdk default java 17.0.3-ms
    command: |
      docker ps
      gp ports await 3306
